version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - '9000:9000'
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
        depends_on:
            - mysql

    nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./:/var/www/html
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./ssl/eitm-sp.crt:/etc/ssl/certs/eitm-sp.crt
        - ./ssl/eitm-sp.key:/etc/ssl/private/eitm-sp.key
      depends_on:
        - app
        - mysql
      networks:
        - app-network

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
      driver: local
